name: Full-Stack CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-deploy:
    name: Backend CI/CD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run backend tests
        working-directory: ./backend
        run: npm test
        env:
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}

      - name: Deploy to Render (optional)
        if: github.event_name == 'push'
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

  frontend-deploy:
    name: Frontend CI/CD
    runs-on: ubuntu-latest
    needs: backend-deploy
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      - name: Deploy to Vercel (optional)
        if: github.event_name == 'push'
        run: curl -X POST ${{ secrets.VERCEL_DEPLOY_HOOK }}
